### ISSUE TITLE
Missing region in config error

### ISSUE THREAD

**Issue by osazemeu** [nxtlvlgg/loopback-connector-aws-ses#1]
I have been trying to get this to work to no avail. I keep getting the following error message.

/datasources.json
```
 "aws-ses": {
    "name": "aws-ses",
    "connector": "loopback-connector-aws-ses",
    "transports": [{
      "accessKeyId": "KEY",
      "secretAccessKey": "SECRET",
      "region": "us-west-2"
    }]
  }
```

/model-config.js
```
  "Email": {
    "dataSource": "aws-ses",
    "public": false
  }
```

/models/user.js
```
        const params = {
          Destination: {
            ToAddresses: [
              'grime@holla.com',
            ]},
          Message: {
            Body: {
              Html: {
                Charset: 'UTF-8',
                Data: 'This message body contains HTML formatting.\
                It can, for example, contain links like this one: <a class=\
                "ulink\" href=\"http://docs.aws.amazon.com/ses/latest/DeveloperGuide\" target=\
                "_blank\">Amazon SES Developer Guide</a>.',
              },
              Text: {
                Charset: 'UTF-8',
                Data: 'This is the message body in text format.',
              },
            },
            Subject: {
              Charset: 'UTF-8',
              Data: 'Test email',
            },
          },
          ReturnPath: '',
          ReturnPathArn: '',
          Source: 'no-reply@holla.com',
          SourceArn: '',
        };

        User.app.models.Email.send(params, function(err) {
          if (err) return console
            .log(err);
          console
            .log('> sending password reset email to:');
        });
```

```
{ ConfigError: Missing region in config
    at Request.VALIDATE_REGION (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\event_listeners.js:91:45)
    at Request.callListeners (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at callNextListener (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\event_listeners.js:85:9
    at finish (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\config.js:320:7)
    at C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\config.js:338:9
    at SharedIniFileCredentials.get (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\credentials.js:126:7)
    at getAsyncCredentials (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\config.js:332:24)
    at Config.getCredentials (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\config.js:352:9)
    at Request.VALIDATE_CREDENTIALS (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\event_listeners.js:80:26)
    at Request.callListeners (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\sequential_executor.js:101:18)
    at Request.emit (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at Request.runTo (C:\Users\ARNERGY\Documents\arnergy-projects\solarbase-loopback\node_modules\aws-sdk\lib\request.js:403:15)
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2018-03-19T17:05:29.035Z }
```

I keep getting this error message, missing region in config. How do I fix this?

**Comment by luncht1me** [comment]
@osazemeu 

Here's an example of my datasources.json using this connector. 

```json
	"aws-ses": {
		"name": "aws-ses",
		"connector": "loopback-connector-aws-ses",
		"key": "KEY",
		"secret": "SECRET",
		"region": "us-west-2"
	},
```

I think your error is wrapping the stuff in a 'transports' block. Try flattening out the datasources object like so and try again.

Also, I suggest you edit your post and remove your api keys my dude.

**Comment by osazemeu** [comment]
Thanks for the assistance. I have another error that I have been trying to fix to no avail but will open another issue for this.
